=== bp2014n2/i2b2/edu.harvard.i2b2.xml/xsd/hive/pdo/i2b2_PDO.xsd
<?xml version="1.0" encoding="UTF-8"?>  
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
    xmlns:pdo="http://www.i2b2.org/xsd/hive/pdo/"
    targetNamespace="http://www.i2b2.org/xsd/hive/pdo/">


    <xs:include schemaLocation="./i2b2_PDO_fields.xsd"/>

    <xs:element name="patient_data" type="pdo:patient_dataType">
        <xs:annotation>
            <xs:documentation>The root element that holds data from the patient data
            tables.</xs:documentation>
        </xs:annotation>
    </xs:element>
    <xs:complexType name="patient_dataType">
        <xs:annotation>
            <xs:documentation>May contain any number of visit_dimension, concept_dimension,
                provider_dimension, patient_dimension and observation_fact elements. They can occur
                in any order.</xs:documentation>
        </xs:annotation>
        <xs:sequence>
            <xs:element name="visit_dimension_set" minOccurs="0">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="visit_dimension" maxOccurs="unbounded"
                            type="pdo:visit_dimensionType"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
            <xs:element name="concept_dimension_set" minOccurs="0">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="concept_dimension" maxOccurs="unbounded"
                            type="pdo:concept_dimensionType"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
            <xs:element name="provider_dimension_set" minOccurs="0">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="provider_dimension" maxOccurs="unbounded"
                            type="pdo:provider_dimensionType"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
            <xs:element name="patient_dimension_set" minOccurs="0">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="patient_dimension" maxOccurs="unbounded"
                            type="pdo:patient_dimensionType"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
            <xs:element name="observation_fact_set" minOccurs="0" maxOccurs="unbounded">
            
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="observation_fact" maxOccurs="unbounded"
                            type="pdo:observation_factType"/>
                    </xs:sequence>
                     
                    <xs:attribute name="path" type="xs:string" use="optional"/>
                    <xs:attribute name="filter_name" type="xs:string" use="optional"/>
                    <xs:attribute name="concept_name" type="xs:string" use="optional"/>
                    <xs:attribute name="provider_id" type="xs:string" use="optional"/>
                    <!--
                    <xs:attributeGroup ref="pdo:conceptPathgroup"/>
    		        <xs:attributeGroup ref="pdo:providerPathgroup"/>
    		        -->
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="visit_dimensionType">
        <xs:annotation>
            <xs:documentation>One row of data from the visit_dimension table.</xs:documentation>
        </xs:annotation>
        <xs:sequence>
            <xs:group ref="pdo:encounter_idChoice"/>
            <xs:group ref="pdo:patient_idChoice"/>
            <xs:element name="inout_cd" type="pdo:InOut_CdType" minOccurs="0"/>
            <xs:element name="location_cd" type="pdo:Location_CdType" minOccurs="0"/>
            <xs:element name="location_path" type="pdo:Location_PathType" minOccurs="0"/>
            <xs:element name="start_date" type="pdo:Start_DateType" minOccurs="0"/>
            <xs:element name="end_date" type="pdo:End_DateType" minOccurs="0"/>
            <xs:element name="visit_blob" type="pdo:Visit_BlobType" minOccurs="0"/>
            <xs:group ref="pdo:annotationGroup"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="concept_dimensionType">
        <xs:annotation>
            <xs:documentation>One row of data from the concept_dimension table.</xs:documentation>
        </xs:annotation>
        <xs:sequence>
            <xs:element name="concept_path" type="pdo:Concept_PathType"/>
            <xs:element name="concept_cd" type="pdo:Concept_CdType" minOccurs="0"/>
            <xs:element name="name_char" type="pdo:Name_CharType" minOccurs="0"/>
            <xs:element name="concept_blob" type="pdo:Concept_BlobType" minOccurs="0"/>
            <xs:group ref="pdo:annotationGroup"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="provider_dimensionType">
        <xs:annotation>
            <xs:documentation>One row of data from the provider_dimension table.</xs:documentation>
        </xs:annotation>
        <xs:sequence>
            <xs:element name="provider_path" type="pdo:Provider_PathType"/>
            <xs:element name="provider_id" type="pdo:Provider_IdType"/>
            <xs:element name="name_char" type="pdo:Name_CharType" minOccurs="0"/>
            <xs:element name="provider_blob" type="pdo:Provider_BlobType" minOccurs="0"/>
            <xs:group ref="pdo:annotationGroup"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="patient_dimensionType">
        <xs:annotation>
            <xs:documentation>One row of data from the patient_dimension table.</xs:documentation>
        </xs:annotation>
        <xs:sequence>
            <xs:group ref="pdo:patient_idChoice"/>
            <xs:element name="vital_status_cd" type="pdo:Vital_Status_CdType" minOccurs="0"/>
            <xs:element name="birth_date" type="pdo:Birth_DateType" minOccurs="0"/>
            <xs:element name="death_date" type="pdo:Death_DateType" minOccurs="0"/>
            <xs:element name="sex_cd" type="pdo:Sex_CdType" minOccurs="0"/>
            <xs:element name="age_in_years_num" type="pdo:Age_In_Years_NumType" minOccurs="0"/>
            <xs:element name="language_cd" type="pdo:Language_CdType" minOccurs="0"/>
            <xs:element name="race_cd" type="pdo:Race_CdType" minOccurs="0"/>
            <xs:element name="marital_status_cd" type="pdo:Marital_Status_CdType" minOccurs="0"/>
            <xs:element name="religion_cd" type="pdo:Religion_CdType" minOccurs="0"/>
            <xs:element name="zip_cd" type="pdo:Zip_CdType" minOccurs="0"/>
            <xs:element name="statecityzip_path" type="pdo:StateCityZip_PathType" minOccurs="0"/>
            <xs:element name="patient_blob" type="pdo:Patient_BlobType" minOccurs="0"/>
            <xs:group ref="pdo:annotationGroup"/>
        </xs:sequence>
    </xs:complexType>
    <!--
    <xs:group name="observationSetGroupChoice">
		<xs:sequence>
			<xs:choice>
        	<xs:attributeGroup ref="conceptPathgroup"/>
        	</xs:choice>
        	
    		<xs:attributeGroup ref="providerPathgroup"/>
    		
		</xs:sequence>
    </xs:group>
	<xs:attributeGroup name="conceptPathgroup">
	  <xs:attribute name="concept_name" type="xs:string"/>
	  <xs:attribute name="concept_path" type="xs:string"/>
	</xs:attributeGroup>
	<xs:attributeGroup name="providerPathgroup">
	  <xs:attribute name="provider_name" type="xs:string"/>
	  <xs:attribute name="provider_path" type="xs:string"/>
	</xs:attributeGroup>
	-->
    <xs:complexType name="observation_factType">
        <xs:annotation>
            <xs:documentation>One row of data from the observation_fact table.</xs:documentation>
        </xs:annotation>
        <xs:sequence>
            <xs:group ref="pdo:encounter_idChoice" minOccurs="1"/>
            <xs:group ref="pdo:patient_idChoice" minOccurs="1"/>
            <xs:element name="concept_cd" type="pdo:Concept_CdType"/>
            <xs:element name="provider_id" type="pdo:Provider_IdType"/>
            <xs:element name="start_date" type="pdo:Start_DateType"/>
            <xs:element name="modifier_cd" type="pdo:Modifier_CdType"/>
            <xs:element name="valtype_cd" type="pdo:ValType_CdType" minOccurs="0"/>
            <xs:element name="tval_char" type="pdo:TVal_CharType" minOccurs="0"/>
            <xs:element name="nval_num" type="pdo:NVal_NumType" minOccurs="0"/>
            <xs:element name="valueflag_cd" type="pdo:ValueFlag_CdType" minOccurs="0"/>
            <xs:element name="quantity_num" type="pdo:Quantity_NumType" minOccurs="0"/>
            <xs:element name="units_cd" type="pdo:Units_CdType" minOccurs="0"/>
            <xs:element name="end_date" type="pdo:End_DateType" minOccurs="0"/>
            <xs:element name="location_cd" type="pdo:Location_CdType" minOccurs="0"/>
            <xs:element name="confidence_num" type="pdo:Confidence_NumType" minOccurs="0"/>
            <!--
            <xs:element name="observation_blob" type="pdo:Observation_BlobType" minOccurs="0"/>
            -->
            <xs:element name="observation_blob" type="xs:anyType" minOccurs="0"/>
            <xs:group ref="pdo:annotationGroup" minOccurs="0"/>
        </xs:sequence>
    </xs:complexType>
    <xs:group name="patient_idChoice">
        <xs:annotation>
            <xs:documentation>A choice between one of three patient identifiers.</xs:documentation>
        </xs:annotation>
        <xs:choice>
            <xs:element name="patient_num" type="pdo:Patient_NumType"/>
            <xs:element name="patient_id" type="pdo:Patient_IdType"/>
            <xs:element name="patient_ide" type="pdo:Patient_IdeType"/>
        </xs:choice>
    </xs:group>
    <xs:group name="encounter_idChoice">
        <xs:annotation>
            <xs:documentation>A choice between one of three encounter
            identifiers.</xs:documentation>
        </xs:annotation>
        <xs:choice>
            <xs:element name="encounter_num" type="pdo:Encounter_NumType"/>
            <xs:element name="encounter_id" type="pdo:Encounter_IdType"/>
            <xs:element name="encounter_ide" type="pdo:Encounter_IdeType"/>
        </xs:choice>
    </xs:group>
    <xs:group name="annotationGroup">
        <xs:annotation>
            <xs:documentation>A group of fields that always appear together at the end of a table
                and store annotation or administrative information.</xs:documentation>
        </xs:annotation>
        <xs:sequence>
            <xs:element name="update_date" type="pdo:Update_DateType" minOccurs="0"/>
            <xs:element name="download_date" type="pdo:Download_DateType" minOccurs="0"/>
            <xs:element name="import_date" type="pdo:Import_DateType" minOccurs="0"/>
            <xs:element name="sourcesystem_cd" type="pdo:Sourcesystem_CdType" minOccurs="0"/>
            <xs:element name="upload_id" type="pdo:Upload_IdType" minOccurs="0"/>
        </xs:sequence>
    </xs:group>
</xs:schema>

=== bp2014n2/i2b2/edu.harvard.i2b2.xml/xsd/hive/pdo/i2b2_PDO.xml
<?xml version="1.0" encoding="UTF-8"?>
<pdo:patient_data xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:pdo="http://www.i2b2.org/xsd/hive/pdo/"
    xsi:schemaLocation="http://www.i2b2.org/xsd/hive/pdo/ ./i2b2_PDO.xsd">

    <visit_dimension_set>

        <!-- Maximum Visit Data -->
        <visit_dimension>
            <encounter_ide source="PULENCTMAP">XDFD45HSDG9578FDFG</encounter_ide>
            <patient_num>12345</patient_num>
            <inout_cd>I</inout_cd>
            <location_cd>MGH</location_cd>
            <location_path>Clinics\MGH\Oral Surgury</location_path>
            <start_date>1999-02-28T13:59:00</start_date>
            <end_date>1999-02-28T13:59:00</end_date>
            <visit_blob/>
            <update_date>1999-02-28T13:59:00</update_date>
            <download_date>1999-02-28T13:59:00</download_date>
            <import_date>1999-02-28T13:59:00</import_date>
            <sourcesystem_cd>RPDRASTHMA</sourcesystem_cd>
            <upload_id>123</upload_id>
        </visit_dimension>

        <!-- Minimum Visit Data -->
        <visit_dimension>
            <encounter_num>1234567</encounter_num>
            <patient_id source="EMP">123456789</patient_id>
        </visit_dimension>

    </visit_dimension_set>

    <concept_dimension_set>

        <!-- Maximum Concept Data -->
        <concept_dimension>
            <concept_path>i2b2\Diagnoses\C0004096</concept_path>
            <concept_cd>UMLS:C0004096</concept_cd>
            <name_char>Asthma</name_char>
            <concept_blob/>
            <update_date>1999-02-28T13:59:00</update_date>
            <download_date>1999-02-28T13:59:00</download_date>
            <import_date>1999-02-28T13:59:00</import_date>
            <sourcesystem_cd>ASTHMADICT</sourcesystem_cd>
            <upload_id>234</upload_id>
        </concept_dimension>

        <!-- Minimum Concept Data -->
        <concept_dimension>
            <concept_path>i2b2\Diagnoses\C0004096</concept_path>
        </concept_dimension>

    </concept_dimension_set>

    <provider_dimension_set>

        <!-- Maximum Provider Data -->
        <provider_dimension>
            <provider_path>BWH\Pathology\B001234567\12345</provider_path>
            <provider_id>B001234567</provider_id>
            <name_char>Doctor, John A., MD</name_char>
            <provider_blob/>
            <update_date>1999-02-28T13:59:00</update_date>
            <download_date>1999-02-28T13:59:00</download_date>
            <import_date>1999-02-28T13:59:00</import_date>
            <sourcesystem_cd>token</sourcesystem_cd>
            <upload_id>345</upload_id>
        </provider_dimension>

        <!-- Minimum Provider Data -->
        <provider_dimension>
            <provider_path>BWH\Pathology\B001234567\12345</provider_path>
            <provider_id>B001234567</provider_id>
        </provider_dimension>

    </provider_dimension_set>

    <patient_dimension_set>

        <!-- Maximum Patient Data -->
        <patient_dimension>
            <patient_id source="EMP">123456789</patient_id>
            <vital_status_cd>Y</vital_status_cd>
            <birth_date>1930-02-28T13:59:00</birth_date>
            <death_date>2001-02-28T13:59:00</death_date>
            <sex_cd>F</sex_cd>
            <age_in_years_num>71</age_in_years_num>
            <language_cd>ENGL</language_cd>
            <race_cd>B</race_cd>
            <marital_status_cd>M</marital_status_cd>
            <religion_cd>CA</religion_cd>
            <zip_cd>12345-1234</zip_cd>
            <statecityzip_path>Zip codes\Massachusetts\Boston\02120\</statecityzip_path>
            <patient_blob/>
            <update_date>1999-02-28T13:59:00</update_date>
            <download_date>1999-02-28T13:59:00</download_date>
            <import_date>1999-02-28T13:59:00</import_date>
            <sourcesystem_cd>token</sourcesystem_cd>
            <upload_id>456</upload_id>
        </patient_dimension>

        <!-- Minimum Patient Data -->
        <patient_dimension>
            <patient_num>1234</patient_num>
        </patient_dimension>

    </patient_dimension_set>

    <observation_fact_set>

        <!-- Maximum Observation Data -->
        <observation_fact>
            <encounter_num>1234567</encounter_num>
            <patient_ide source="EMP">XRTU8GT9FKIS35DSVB</patient_ide>
            <concept_cd>CODING-SYSTEM:V450</concept_cd>
            <provider_id>12345</provider_id>
            <start_date>1999-02-28T13:59:00</start_date>
            <modifier_cd/>
            <valtype_cd>N</valtype_cd>
            <tval_char>Some Text Value</tval_char>
            <nval_num>1.0</nval_num>
            <valueflag_cd>float (or some code)</valueflag_cd>
            <quantity_num>1.0</quantity_num>
            <units_cd>ml</units_cd>
            <end_date>1999-02-28T13:59:00</end_date>
            <location_cd>MGH</location_cd>
            <confidence_num>95</confidence_num>
            <observation_blob/>
            <update_date>1999-02-28T13:59:00</update_date>
            <download_date>1999-02-28T13:59:00</download_date>
            <import_date>1999-02-28T13:59:00</import_date>
            <sourcesystem_cd>RPDRASTHMA</sourcesystem_cd>
            <upload_id>567</upload_id>
        </observation_fact>

        <!-- Minimum Observation Data -->
        <observation_fact>
            <encounter_id source="PULENCTMAP">123456</encounter_id>
            <patient_num>1234</patient_num>
            <concept_cd>CODING-SYSTEM:V450</concept_cd>
            <provider_id>12345</provider_id>
            <start_date>1999-02-28T13:59:00</start_date>
            <modifier_cd/>
            <observation_blob></observation_blob>
        </observation_fact>

    </observation_fact_set>
    
    <observation_fact_set concept_name="1" concept_path="1">
        <observation_fact>
            <encounter_num>1</encounter_num>
            <patient_num>1</patient_num>
            <concept_cd>1</concept_cd>
            <provider_id></provider_id>
            <start_date>1999-02-28T13:59:00</start_date>
            <modifier_cd></modifier_cd>
        </observation_fact>
    </observation_fact_set>

</pdo:patient_data>
