=== bp2014n2/i2b2/edu.harvard.i2b2.xml/xsd/cell/id/ID_publish.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
    xmlns:id="http://www.i2b2.org/xsd/cell/id/"
    targetNamespace="http://www.i2b2.org/xsd/cell/id/">

    <!-- <xs:import schemaLocation="i2b2.xsd" namespace="http://i2b2.mgh.harvard.edu/message"/> -->
    <xs:include schemaLocation="ID_identity.xsd"/>

    <xs:element name="publish">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="request" type="id:publish_requestType"/>
                <xs:element name="response" type="id:publish_responseType"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:complexType name="messageType">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute name="status">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:enumeration value="no_change"/>
                            <xs:enumeration value="inserted_new"/>
                            <xs:enumeration value="updated_existing"/>
                            <xs:enumeration value="error"/>
                            <xs:enumeration value="no_master_created"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:attribute>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>

    <xs:complexType name="publish_requestType">
        <xs:choice minOccurs="1" maxOccurs="unbounded">
            <xs:element name="master_record" type="id:master_recordType"/>
        </xs:choice>
        <xs:attribute name="session" type="xs:string" use="optional"/>
    </xs:complexType>

    <xs:group name="recordGroup">
        <xs:choice>
            <xs:element name="string" type="id:stringType"/>
            <xs:element name="date" type="id:dateType"/>
            <xs:element name="datetime" type="id:datetimeType"/>
            <xs:element name="number" type="id:numberType"/>
        </xs:choice>
    </xs:group>

    <xs:complexType name="master_recordType">
        <xs:choice minOccurs="0" maxOccurs="1">
            <xs:group ref="id:recordGroup" maxOccurs="unbounded"/>
            <xs:element name="local_record" type="id:local_recordType" maxOccurs="unbounded"/>
        </xs:choice>
        <xs:attribute name="id" type="xs:string" use="optional"/>
        <xs:attribute name="status">
            <xs:simpleType>
                <xs:restriction base="xs:string">
                    <xs:enumeration value="active"/>
                    <xs:enumeration value="inactive"/>
                </xs:restriction>
            </xs:simpleType>
        </xs:attribute>
    </xs:complexType>

    <xs:complexType name="local_recordType">
        <xs:group ref="id:recordGroup" minOccurs="0" maxOccurs="unbounded"/>
        <xs:attribute name="site" type="xs:string" use="required"/>
        <xs:attribute name="id" type="xs:string" use="required"/>
        <xs:attribute name="status">
            <xs:simpleType>
                <xs:restriction base="xs:string">
                    <xs:enumeration value="active"/>
                    <xs:enumeration value="inactive"/>
                </xs:restriction>
            </xs:simpleType>
        </xs:attribute>
    </xs:complexType>

    <xs:complexType name="publish_responseType">
        <xs:sequence>
            <xs:element name="publish_master" maxOccurs="unbounded">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="message" type="id:messageType"/>
                        <xs:element name="publish_local" maxOccurs="unbounded">
                            <xs:complexType>
                                <xs:sequence>
                                    <xs:element name="message" type="id:messageType"/>
                                </xs:sequence>
                                <xs:attribute name="id" type="xs:string" use="required"/>
                                <xs:attribute name="site" type="xs:string" use="required"/>
                            </xs:complexType>
                        </xs:element>
                    </xs:sequence>
                    <xs:attribute name="session" type="xs:string" use="optional"/>
                    <xs:attribute name="id" type="xs:string" use="optional"/>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>

</xs:schema>

=== bp2014n2/i2b2/edu.harvard.i2b2.xml/xsd/cell/id/ID_publish.xml
<?xml version="1.0" encoding="UTF-8"?>
<id:publish xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:id="http://www.i2b2.org/xsd/cell/id/"
    xsi:schemaLocation="http://www.i2b2.org/xsd/cell/id/ ./ID_publish.xsd">
    <request session="x">
        <master_record id="1">
            <local_record id="a" site="lmr" status="active">
                <string concept_cd="first_name">Raj</string>
                <string concept_cd="last_name">Kuttan-Kuttan</string>
                <date concept_cd="birthdate">2000-02-29</date>
                <datetime concept_cd="start_date">2002-02-28T13:59:59</datetime>
                <number concept_cd="test_result">25.0</number>
            </local_record>
            <local_record id="b" site="mgh" status="inactive">
                <string concept_cd="first_name">rajesh</string>
                <string concept_cd="last_name">kuttan</string>
            </local_record>
        </master_record>
        <master_record>
            <local_record id="c" site="bwh">
                <string concept_cd="first_name">Kristel</string>
                <string concept_cd="last_name">Hackett</string>
            </local_record>
        </master_record>
    </request>
    <response>
        <publish_master id="1">
            <message status="error">There was some kind of error.</message>
            <publish_local id="a" site="lmr">
                <message status="error">There was an error with date type.</message>
            </publish_local>
            <publish_local id="b" site="mgh">
                <message status="updated_existing"/>
            </publish_local>
        </publish_master>
        <publish_master>
            <message status="no_master_created"/>
            <publish_local id="c" site="bwh">
                <message status="inserted_new"/>
            </publish_local>
        </publish_master>
    </response>
</id:publish>
